## DataFrame Methods
- df.head(n) - returns the first n rows of the DataFrame
- df.tail(n) - returns the last n rows of the DataFrame
- df.sample(n) - returns a random sample of n rows from the DataFrame
- df.info() - returns a summary of the DataFrame, including the number of non-null values and the data types of each column
- df.shape() - returns the number of rows and columns in the DataFrame in the form of a tuple (rows, columns)
- df.describe() - returns a summary of the numerical columns in the DataFrame, including count, mean, standard deviation, minimum, and maximum values
- df.columns - returns the column names of the DataFrame
- df.nunique() - returns the number of unique values in each column of the DataFrame

In [1]:
import pandas as pd

In [10]:
df = pd.read_json("employee_data.json")
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [9]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [12]:
df.sample(3)

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
8   9    Ian   35         IT   75000
1   2    Bob   32         IT   72000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

In [14]:
df.shape

(10, 5)

In [15]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [21]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [22]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64