In [1]:
import pandas as pd

In [30]:
df = pd.read_csv("raw_data.csv")
df["tax"] = df["income"].apply(lambda x: "20%" if x >= 50_000 else "10%")
gender_map = {"Male" : "M", "Female" : "F"}
df["gender"] = df["gender"].map(gender_map)
df

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA    NaN  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [31]:
df.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax"]
df.rename(columns={"Income": "Salary"}, inplace=False)

    Id          Name   Age Country Gender   Salary  Tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA    NaN  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [37]:
sorted_df = df.sort_values("Income")
sorted_df = sorted_df.reset_index()
sorted_df["Ranking"] = sorted_df["Income"].rank(method = "min")
sorted_df

    index  Id          Name   Age Country Gender   Income  Tax  Ranking
0       9   9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%      1.0
1       3   3          Alex   NaN     USA    NaN  47000.0  10%      2.0
2       5   5        Li Wei  27.0   China      M  51000.0  20%      3.0
3       1   1      John Doe  29.0     USA      M  55000.0  20%      4.0
4       0   1      John Doe  29.0     USA      M  55000.0  20%      4.0
5      10  10   Emily Davis  31.0     USA    NaN  58000.0  20%      6.0
6       2   2    Jane Smith   NaN  Canada      F  62000.0  20%      7.0
7       8   8    Rachel Lee  29.0     USA      F  62000.0  20%      7.0
8       7   7    Ahmed Khan  38.0     NaN      M  68000.0  20%      9.0
9       6   6           NaN  45.0   India      F  73000.0  20%     10.0
10      4   4  Maria Garcia  34.0   Spain      F      NaN  10%      NaN

In [38]:
df = pd.read_csv("raw_data.csv")

In [46]:
df2 = df.copy()
new_col_order = [col for col in df2.columns if col != "id"] + ["id"]
df[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10