In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [6]:
df.groupby("country")["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [8]:
df.groupby("country")["income"].agg(avg_salary = "mean", min_salary = "min", max_salary =  "max")

         avg_salary  min_salary  max_salary
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     47000.0     62000.0

In [9]:
df.groupby("country").agg(avg_salary = ("income", "mean"), min_salary = ("income", "min"), max_salary =  ("income", "max"))

         avg_salary  min_salary  max_salary
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     47000.0     62000.0