### Merging and Joining Data

In [1]:
import pandas as pd

In [2]:
df_orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4],
    'customer_id': [101, 102, 103, 104],
    'amount': [250, 150, 300, 200]
})

df_customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 105],
    'customer_name': ['Alice', 'Bob', 'Charlie', 'David']
})

In [5]:
pd.merge(df_orders, df_customers, on='customer_id')

   order_id  customer_id  amount customer_name
0         1          101     250         Alice
1         2          102     150           Bob
2         3          103     300       Charlie

In [6]:
pd.merge(df_orders, df_customers, on='customer_id', how='left')

   order_id  customer_id  amount customer_name
0         1          101     250         Alice
1         2          102     150           Bob
2         3          103     300       Charlie
3         4          104     200           NaN

In [7]:
pd.merge(df_orders, df_customers, on='customer_id', how='outer')

   order_id  customer_id  amount customer_name
0       1.0          101   250.0         Alice
1       2.0          102   150.0           Bob
2       3.0          103   300.0       Charlie
3       4.0          104   200.0           NaN
4       NaN          105     NaN         David